// <auto-generated />
using System;
using Finort.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finort.Data.Migrations.MySql
{
    [DbContext(typeof(MySqlAppDbContext))]
    [Migration("20260829202422_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Finort.Models.Auth.Configuracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackupPasswordCriptografada")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SmtpFrom")
                        .HasColumnType("longtext");

                    b.Property<string>("SmtpHost")
                        .HasColumnType("longtext");

                    b.Property<string>("SmtpPassword")
                        .HasColumnType("longtext");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("int");

                    b.Property<string>("SmtpUser")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Configuracoes");
                });

            modelBuilder.Entity("Finort.Models.Auth.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfiguracaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ConfiguracaoId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.AuditoriaExclusaoInvestimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DataCotacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataExclusao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeInvestimento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorCotaAtual")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("AuditoriasExclusaoInvestimento");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.CartaoCredito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ContaId")
                        .HasColumnType("char(36)");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("int");

                    b.Property<decimal>("Limite")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("MelhorDiaCompra")
                        .HasColumnType("int");

                    b.Property<string>("Ultimos4Digitos")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("varchar(4)");

                    b.HasKey("Id");

                    b.HasIndex("ContaId");

                    b.ToTable("CartoesCredito");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsProtected")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsProtected = false,
                            Nome = "Contas de casa"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsProtected = false,
                            Nome = "Renda"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsProtected = false,
                            Nome = "Alimentação"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsProtected = false,
                            Nome = "Transporte"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsProtected = false,
                            Nome = "Saúde"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsProtected = false,
                            Nome = "Compras"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            IsProtected = false,
                            Nome = "Educação"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsProtected = false,
                            Nome = "Lazer"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            IsProtected = true,
                            Nome = "Financeiro"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsProtected = false,
                            Nome = "Familia"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            IsProtected = false,
                            Nome = "Impostos"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            IsProtected = false,
                            Nome = "Investimento"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            IsProtected = true,
                            Nome = "Acerto de saldo"
                        });
                });

            modelBuilder.Entity("Finort.Models.Financeiro.Conta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Agencia")
                        .HasColumnType("longtext");

                    b.Property<string>("Banco")
                        .HasColumnType("longtext");

                    b.Property<string>("ContaEDigito")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.Fatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AnoReferencia")
                        .HasColumnType("int");

                    b.Property<Guid>("CartaoCreditoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Fechada")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MesReferencia")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("CartaoCreditoId", "AnoReferencia", "MesReferencia")
                        .IsUnique();

                    b.ToTable("Faturas");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.Investimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ContaVinculadaId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DataCotacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Subtipo")
                        .HasColumnType("longtext");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorCotaAtual")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("ContaVinculadaId");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Investimentos");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.InvestimentoMovimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<Guid>("InvestimentoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("LancamentoId")
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("Quantidade")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ValorPorCota")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("InvestimentoId");

                    b.HasIndex("LancamentoId");

                    b.ToTable("InvestimentosMovimentos");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.InvestimentoProvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<Guid>("InvestimentoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("LancamentoId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("InvestimentoId");

                    b.HasIndex("LancamentoId");

                    b.ToTable("InvestimentosProventos");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.Lancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CartaoCreditoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Confirmado")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("ContaId")
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataCompra")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataVencimentoCartao")
                        .HasColumnType("date");

                    b.Property<int?>("ParcelaAtual")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParcelamentoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("PessoaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProjetoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProvisaoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("RecorrenciaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ReembolsoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ReferenciaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SubcategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int?>("TotalParcelas")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("CartaoCreditoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContaId");

                    b.HasIndex("Data");

                    b.HasIndex("ParcelamentoId");

                    b.HasIndex("PessoaId");

                    b.HasIndex("ProjetoId");

                    b.HasIndex("ProvisaoId");

                    b.HasIndex("RecorrenciaId");

                    b.HasIndex("ReferenciaId");

                    b.HasIndex("SubcategoriaId");

                    b.ToTable("Lancamentos");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.Lembrete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly?>("Data")
                        .HasColumnType("date");

                    b.Property<int?>("Dia")
                        .HasColumnType("int");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("Lembretes");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.MesFechado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataFechamento")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<decimal>("SaldoAcumulado")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("Mes", "Ano")
                        .IsUnique();

                    b.ToTable("MesesFechados");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CorDeExibicao")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observacao")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.Projeto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Concluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly?>("DataConclusao")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataContratacao")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("PessoaId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("ValorContratado")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.Provisao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CartaoCreditoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ContaId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Dia")
                        .HasColumnType("int");

                    b.Property<int>("Frequencia")
                        .HasColumnType("int");

                    b.Property<int>("Onde")
                        .HasColumnType("int");

                    b.Property<Guid?>("PessoaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("SubcategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("UltimoAnoLancado")
                        .HasColumnType("int");

                    b.Property<int?>("UltimoMesLancado")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("ValorVariante")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CartaoCreditoId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContaId");

                    b.HasIndex("PessoaId");

                    b.HasIndex("SubcategoriaId");

                    b.ToTable("Provisoes");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.Subcategoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsProtected")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Subcategorias");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsProtected = false,
                            Nome = "Energia"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsProtected = false,
                            Nome = "Água"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000001"),
                            IsProtected = false,
                            Nome = "Internet"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsProtected = false,
                            Nome = "Contrato mensal"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000002"),
                            IsProtected = false,
                            Nome = "Extra"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsProtected = false,
                            Nome = "Mercado"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsProtected = false,
                            Nome = "Açougue"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsProtected = false,
                            Nome = "Feira"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000003"),
                            IsProtected = false,
                            Nome = "Restaurante"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000010"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsProtected = false,
                            Nome = "Combustível"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000011"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsProtected = false,
                            Nome = "Estacionamento"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000012"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsProtected = false,
                            Nome = "Transporte público"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000013"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsProtected = false,
                            Nome = "Uber/99/Taxi"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000014"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsProtected = false,
                            Nome = "Pedágio"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000015"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsProtected = false,
                            Nome = "Manutenção"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000016"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsProtected = false,
                            Nome = "Seguro"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000017"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsProtected = false,
                            Nome = "IPVA/Licenciamento"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000018"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000004"),
                            IsProtected = false,
                            Nome = "Financiamento"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000019"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsProtected = false,
                            Nome = "Plano de saúde"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000020"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsProtected = false,
                            Nome = "Consulta"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000021"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsProtected = false,
                            Nome = "Exame"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000022"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsProtected = false,
                            Nome = "Medicamento"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000023"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000005"),
                            IsProtected = false,
                            Nome = "Dentista"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000024"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsProtected = false,
                            Nome = "Roupa/Calçado"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000025"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsProtected = false,
                            Nome = "Eletrônicos"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000026"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsProtected = false,
                            Nome = "Presente"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000027"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000006"),
                            IsProtected = false,
                            Nome = "Outro"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000028"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000007"),
                            IsProtected = false,
                            Nome = "Curso/Faculdade/Escola"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000029"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000007"),
                            IsProtected = false,
                            Nome = "Livro/Material"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000030"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000007"),
                            IsProtected = false,
                            Nome = "Certificação"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000031"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsProtected = false,
                            Nome = "Cinema/Teatro"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000032"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsProtected = false,
                            Nome = "Shows/eventos"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000033"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsProtected = false,
                            Nome = "Streaming"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000034"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsProtected = false,
                            Nome = "Jogos"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000035"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsProtected = false,
                            Nome = "Viagens"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000036"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000008"),
                            IsProtected = false,
                            Nome = "Outros"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000037"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000009"),
                            IsProtected = false,
                            Nome = "Anuidades/Tarifas"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000038"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000009"),
                            IsProtected = false,
                            Nome = "Juros"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000039"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000009"),
                            IsProtected = false,
                            Nome = "IOF"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000040"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000009"),
                            IsProtected = false,
                            Nome = "Empréstimo"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000041"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000009"),
                            IsProtected = false,
                            Nome = "Financiamento"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000042"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000009"),
                            IsProtected = false,
                            Nome = "Pagamento de dívida"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000043"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000009"),
                            IsProtected = true,
                            Nome = "Transferência"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000044"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsProtected = false,
                            Nome = "Filho"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000045"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsProtected = false,
                            Nome = "Conjugue"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000046"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsProtected = false,
                            Nome = "Pensão"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000047"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000010"),
                            IsProtected = false,
                            Nome = "Outro"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000048"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000011"),
                            IsProtected = false,
                            Nome = "Imposto de renda"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000049"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000011"),
                            IsProtected = false,
                            Nome = "IPTU"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000050"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000011"),
                            IsProtected = false,
                            Nome = "Multas"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000051"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000011"),
                            IsProtected = false,
                            Nome = "Taxas"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000052"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000011"),
                            IsProtected = false,
                            Nome = "Outros impostos"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000053"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000012"),
                            IsProtected = false,
                            Nome = "Dividendos / Rendimentos"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000054"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000012"),
                            IsProtected = false,
                            Nome = "Compra/Aporte"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000055"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000012"),
                            IsProtected = false,
                            Nome = "Venda / Resgate"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000056"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000013"),
                            IsProtected = true,
                            Nome = "Acerto"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000057"),
                            CategoriaId = new Guid("10000000-0000-0000-0000-000000000009"),
                            IsProtected = true,
                            Nome = "Cartão de crédito"
                        });
                });

            modelBuilder.Entity("Finort.Models.Auth.PasswordResetToken", b =>
                {
                    b.HasOne("Finort.Models.Auth.Configuracao", "Configuracao")
                        .WithMany()
                        .HasForeignKey("ConfiguracaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuracao");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.CartaoCredito", b =>
                {
                    b.HasOne("Finort.Models.Financeiro.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.Fatura", b =>
                {
                    b.HasOne("Finort.Models.Financeiro.CartaoCredito", "CartaoCredito")
                        .WithMany()
                        .HasForeignKey("CartaoCreditoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CartaoCredito");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.Investimento", b =>
                {
                    b.HasOne("Finort.Models.Financeiro.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaVinculadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.InvestimentoMovimento", b =>
                {
                    b.HasOne("Finort.Models.Financeiro.Investimento", "Investimento")
                        .WithMany()
                        .HasForeignKey("InvestimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Finort.Models.Financeiro.Lancamento", "Lancamento")
                        .WithMany()
                        .HasForeignKey("LancamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Investimento");

                    b.Navigation("Lancamento");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.InvestimentoProvento", b =>
                {
                    b.HasOne("Finort.Models.Financeiro.Investimento", "Investimento")
                        .WithMany()
                        .HasForeignKey("InvestimentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Finort.Models.Financeiro.Lancamento", "Lancamento")
                        .WithMany()
                        .HasForeignKey("LancamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Investimento");

                    b.Navigation("Lancamento");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.Lancamento", b =>
                {
                    b.HasOne("Finort.Models.Financeiro.CartaoCredito", "CartaoCredito")
                        .WithMany()
                        .HasForeignKey("CartaoCreditoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Finort.Models.Financeiro.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Finort.Models.Financeiro.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Finort.Models.Financeiro.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Finort.Models.Financeiro.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Finort.Models.Financeiro.Subcategoria", "Subcategoria")
                        .WithMany()
                        .HasForeignKey("SubcategoriaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CartaoCredito");

                    b.Navigation("Categoria");

                    b.Navigation("Conta");

                    b.Navigation("Pessoa");

                    b.Navigation("Projeto");

                    b.Navigation("Subcategoria");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.Lembrete", b =>
                {
                    b.HasOne("Finort.Models.Financeiro.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.Projeto", b =>
                {
                    b.HasOne("Finort.Models.Financeiro.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.Provisao", b =>
                {
                    b.HasOne("Finort.Models.Financeiro.CartaoCredito", "CartaoCredito")
                        .WithMany()
                        .HasForeignKey("CartaoCreditoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Finort.Models.Financeiro.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Finort.Models.Financeiro.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Finort.Models.Financeiro.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Finort.Models.Financeiro.Subcategoria", "Subcategoria")
                        .WithMany()
                        .HasForeignKey("SubcategoriaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CartaoCredito");

                    b.Navigation("Categoria");

                    b.Navigation("Conta");

                    b.Navigation("Pessoa");

                    b.Navigation("Subcategoria");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.Subcategoria", b =>
                {
                    b.HasOne("Finort.Models.Financeiro.Categoria", "Categoria")
                        .WithMany("Subcategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Finort.Models.Financeiro.Categoria", b =>
                {
                    b.Navigation("Subcategorias");
                });
#pragma warning restore 612, 618
        }
    }
}
